name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npm test"
        env:
          PERCY_TOKEN: "web_573c19fded9d82d4d6286fea87e428f17bb65dc60db62284ad36d9de7aae702d"

